language: node_js
install:
  - "npm install mocha"
  - "npm install sinon"
  - "npm install chai"
  - "npm install chai-as-promised"
  - "npm install aws-sdk"
  - "npm install"
  - "npm run eslint"

node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

notifications:
  email:
    recipients:
      - team@jovo.tech
    on_success: never
    on_failure: always

